Repository Plataforma-29-de-abril/29-april-frontend, pull requests merged in 2024-01, with the labels that each got.

#3 #1: Ajustada responsividade da tela de login
  src/pages/Login/index.jsx
Labels: enhancement, Front End

#6 5 ajustar responsividade da tela de recuperação de senha
  src/api/default.js
  src/pages/ChangePassword/index.jsx
  src/pages/RecoverPassword/index.jsx
Labels: enhancement, Front End

#7 Ajustado problema no botão de cadastro
  src/pages/Register/index.jsx
Labels: bug, Front End

#13 9 ajustar responsividade da tela de detalhes do curso
  src/pages/CourseDetails/course_details.css
  src/pages/CourseDetails/course_details.jsx
Labels: enhancement, Front End

#14 #2 Tela de perfil do aluno responsiva
  src/pages/UserProfile/index.jsx
  src/pages/UserProfile/style.css
Labels: Front End
